# Generated by Django 4.0.4 on 2022-05-30 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mifamilia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='edad',
            field=models.CharField(max_length=3),
        ),
    ]
